StudManage1/Controllers/HomePage1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudManage.Models
{
    public class HomePage1Controller : Controller
    {
        // GET: HomePage1
     
        public ActionResult Menu()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View();
        }
        public ActionResult Album()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult calendar()
        {
            return View();
        }
    }
}

StudManage1/Controllers/PlacementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;
using StudManage1.Models;

namespace WebApplication1.Controllers
{
    public class PlacementController : Controller
    {
        // GET: Branch
        public ActionResult Companies()
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            List<company> lb = db.companies.ToList();

            return View(lb);
        }

        public ActionResult Students(int compid, string searchString)
        {

            StudentManagement1Entities db = new StudentManagement1Entities();
            //List<stuDetail> lb = db.stuDetails.Where(s => s.cid == compid).ToList();
            var ModelList = new List<stuDetail>();

            using (var context = new StudentManagement1Entities())
            {
                var model = from s in context.stuDetails
                            select s;
                //Added this area to, Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.name.Contains(searchString)
                                           || s.gender.Contains(searchString));

                }
                model = model.OrderBy(s => s.name);
                ModelList = model.Where(s => s.cid == compid).ToList();


                return View(ModelList);

            }
        }



        public ActionResult Studentdeet(int stid)
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            stuDetail st = db.stuDetails.FirstOrDefault(s => s.sid == stid);

            return View(st);
           
        }

    }
}

StudManage1/Views/Placement/Companies.cshtml
@model IEnumerable<StudManage1.Models.company>
@using StudManage1.Models

@{ ViewBag.Title = "companies"; }

<h2>Companies</h2>

<style>
    div.w3-col {
        display: flex;
        padding: 25px;
        text-align: center;
        align-content: center
    }

    div.w3-container {
        background-color: white;
        /*border-radius: 20px;*/
    }

    img {
        width: 200px;
        height: 100px;
        align-content: center
    }

    a.option {
        border: 0px hidden gray;
        /*border-style: groove;*/
        margin: 10px;
        transition: transform .2s;
        color: blue;
        position: center;
        padding-bottom: 0px;
        align-content: center;
    }

    a:hover {
        transform: scale(1.3);
    }
</style>

@*Students?compid=1*@

<div class="w3-col l3 s6">
    <a class="option" href="~/Placement/Students?compid=1">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/9/9d/KPMG_logo.svg">
            <p><b>KPMG</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=2">
        <div class="w3-container">
            <img src="https://www.pngfind.com/pngs/m/682-6829362_wipro-wipro-logo-hd-png-download.png">
            <p><b>WIPRO</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=3">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Paytm_Logo_%28standalone%29.svg/1200px-Paytm_Logo_%28standalone%29.svg.png">
            <p><b>PAYTM</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=4">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg">
            <p><b>APPLE</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=5">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/368px-Google_2015_logo.svg.png">
            <p><b>GOOGLE</b></p>
        </div>
    </a>
</div>
<div class="w3-col l3 s6">

    <a class="option" href="~/Placement/Students?compid=6">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Larsen%26Toubro_logo.svg/1200px-Larsen%26Toubro_logo.svg.png">
            <p><b>L&T</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=7">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1280px-Infosys_logo.svg.png">
            <p><b>INFOSYS</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=8">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/2560px-Accenture.svg.png">
            <p><b>ACCENTURE</b></p>
        </div>
    </a>
    <a class="option" href="~/Placement/Students?compid=9">
        <div class="w3-container">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Dell_Logo.svg/2048px-Dell_Logo.svg.png">
            <p><b>DELL</b></p>
        </div>
    </a>
</div>

@Html.ActionLink("BACK TO MENU", "menu", "HomePage1")

StudManage1/Views/Placement/Studentdeet.cshtml
@model StudManage1.Models.stuDetail

@{
    ViewBag.Title = "Studentdeet";
}

<h2>Studentdeet</h2>

<div>
    <h4>stuDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            
            Roll Number :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rollNo)
        </dd>

        <dt>
           Name:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            Age:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            Address:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            Phone Number:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNo)
        </dd>

        <dt>
            Date of Birth:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            Gender:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            City:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            Branch:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.branch.b_name)
        </dd>

        <dt>
           Placed at:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company.cname)
        </dd>
     </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.sid }) |
    @Html.ActionLink("Back to List", "menu2","HomePage1")
</p>

StudManage1/Views/Placement/Students.cshtml
@model IEnumerable<StudManage1.Models.stuDetail>
@using StudManage1.Models

@{
    ViewBag.Title = "stulist";
}

<h2>list</h2>
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}


<ul>

    @foreach (stuDetail stuDetail in Model)

    {
        <li>

            @Html.ActionLink(stuDetail.name, "Studentdeet", "Placement", new { stid = stuDetail.sid }, null)

        </li>
    }
</ul>

<p>

    @Html.ActionLink("Back to List", "Companies", "Placement")
</p>