StudManage1/Controllers/regController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudManage1.Models;
namespace StudManage1.Controllers
{
    public class regController : Controller
    {
        // GET: reg
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(stuDetail student)
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            if (ModelState.IsValid)
            {
                student.cid = 10;
                db.stuDetails.Add(student);
                db.SaveChanges();
                TempData["id"] = student.sid;
                return RedirectToAction("Create");

            }

            return View(student);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(eduDetail student)
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            if (ModelState.IsValid)
            {

                student.id = Convert.ToInt32(TempData["id"]);
                db.eduDetails.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index", "stuDetails");

            }

            return View(student);

        }
        public ActionResult Index1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index1(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/fileupload"), filename);
                    file.SaveAs(_path);
                }
                ViewBag.Message = "file uploaded";
                return View();
            }
            catch
            {
                ViewBag.Message = "file uploading failed";
                return View();
            }

        }
        public ActionResult Index2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index2(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/fileupload1"), filename);
                    file.SaveAs(_path);
                }
                ViewBag.Message = "file uploaded";
                return View();
            }
            catch
            {
                ViewBag.Message = "file uploading failed";
                return View();
            }

        }
        public ActionResult CheckUserNameExists(string rollNo)

        {

            bool UserExists = false;



            try

            {

                using (var dbcontext = new StudentManagement1Entities())

                {

                    var nameexits = from temprec in dbcontext.stuDetails

                                    where temprec.rollNo.Equals(rollNo.Trim())

                                    select temprec;

                    if (nameexits.Count() > 0)

                    {

                        UserExists = true;

                    }

                    else

                    {

                        UserExists = false;

                    }

                }

                return Json(!UserExists, JsonRequestBehavior.AllowGet);

            }

            catch (Exception)

            {

                return Json(false, JsonRequestBehavior.AllowGet);

            }

        }
    }

}

StudManage1/Views/reg/Create.cshtml
@model StudManage1.Models.eduDetail

@{
    ViewBag.Title = "Create";
}

<h2>Education Details</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>eduDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--<div class="form-group">
            @Html.LabelFor(model => model.id, "id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })-->
        @*@Html.DropDownList("id", null, htmlAttributes: new { @class = "form-control" })*@
        <!--@Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            @Html.LabelFor(model => model.ten_percent,"10th Percentage", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten_percent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten_percent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ten_yop,"Year of Passing 10th", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ten_yop", new List<SelectListItem>
      {
          new SelectListItem{Text="2010",Value="2010",Selected=true },
          new SelectListItem{Text="2011",Value="2011" },
             new SelectListItem{Text="2012",Value="2012" },
                new SelectListItem{Text="2013",Value="2013" },
                   new SelectListItem{Text="2014",Value="2014" },
                      new SelectListItem{Text="2015",Value="2015" },
                         new SelectListItem{Text="2016",Value="2016" },
                            new SelectListItem{Text="2017",Value="2017" },
                            new SelectListItem{Text="2018",Value="2018" },
                               new SelectListItem{Text="2019",Value="2019" },
               new SelectListItem{Text="2020",Value="2020" }
          })
                @*@Html.EditorFor(model => model.ten_yop, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.ten_yop, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.ten_inst,"10th Passing Institution ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten_inst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten_inst, "", new { @class = "text-danger" })
                @Html.ActionLink("UPLOAD YOUR 10TH MARKSHEET", "Index1", "reg")
                [Note:Your file name should be your rollno followed 10th standard]
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.twel_percent, "12th Percentage", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.twel_percent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.twel_percent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.twel_yop, "Year of Passing 12th", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("twel_yop", new List<SelectListItem>
      {
          new SelectListItem{Text="2010",Value="2010",Selected=true },
          new SelectListItem{Text="2011",Value="2011" },
             new SelectListItem{Text="2012",Value="2012" },
                new SelectListItem{Text="2013",Value="2013" },
                   new SelectListItem{Text="2014",Value="2014" },
                      new SelectListItem{Text="2015",Value="2015" },
                         new SelectListItem{Text="2016",Value="2016" },
                            new SelectListItem{Text="2017",Value="2017" },
                            new SelectListItem{Text="2018",Value="2018" },
                               new SelectListItem{Text="2019",Value="2019" },
               new SelectListItem{Text="2020",Value="2020" }
          })

                @*@Html.EditorFor(model => model.twel_yop, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.twel_yop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.twel_inst, "12th Passing Institution ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.twel_inst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.twel_inst, "", new { @class = "text-danger" })
                @Html.ActionLink("UPLOAD YOUR 12TH MARKSHEET", "Index2", "reg")
                [Note:Your file name should be your rollno followed 12th standard]
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.curr_CGPA, "Current CGPA ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.curr_CGPA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.curr_CGPA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.curr_sem, "Current Semester ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("curr_sem", new List<SelectListItem>
     {
         new SelectListItem{Text="1",Value="1",Selected=true },
         new SelectListItem{Text="2",Value="2" },
            new SelectListItem{Text="3",Value="3" },
               new SelectListItem{Text="4",Value="4" },
                  new SelectListItem{Text="5",Value="5" },
                     new SelectListItem{Text="6",Value="6" },
                        new SelectListItem{Text="7",Value="7" },
                           new SelectListItem{Text="8",Value="8" },

         })
                @*@Html.EditorFor(model => model.curr_sem, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.curr_sem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudManage1/Views/reg/Index.cshtml
@model StudManage1.Models.stuDetail

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>stuDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.branchId, "branchId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("branchId", new List<SelectListItem>
           {
               new SelectListItem{Text="Computer Science",Value="1",Selected=true },
               new SelectListItem{Text="Information Science",Value="2" },
               new SelectListItem{Text="Electronics and Communication",Value="3" },
                new SelectListItem{Text="Mechanical",Value="4" },
                 new SelectListItem{Text="civil",Value="5" }
               })

                @*@Html.EditorFor(model => model.branchId, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownList("branchId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.branchId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rollNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rollNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rollNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Male
                @Html.RadioButtonFor(Model => Model.gender, "Male")
                Female
                @Html.RadioButtonFor(Model => Model.gender, "Female")
                @*@Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("city", new List<SelectListItem>
        {
            new SelectListItem{Text="Bangalore",Value="Bangalore",Selected=true },
            new SelectListItem{Text="Hyderabad",Value="Hyderabad" },
            new SelectListItem{Text="Chennai",Value="Chennai" },
             new SelectListItem{Text="Pune",Value="Pune" },
              new SelectListItem{Text="Delhi",Value="Delhi" }
            })
                @*@Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.cid, "cid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("cid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.cid, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudManage1/Views/reg/Index1.cshtml
@{
    ViewBag.Title = "upload file";
}

<h2>upload file</h2>
@using (Html.BeginForm("Index1", "reg", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("file", "", new { Type = "file" })<br />
        <input type="submit" value="upload" />
        @ViewBag.Message

    </div>
}

StudManage1/Views/reg/Index2.cshtml
@{
    ViewBag.Title = "upload file";
}

<h2>upload file</h2>
@using (Html.BeginForm("Index2", "reg", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("file", "", new { Type = "file" })<br />
        <input type="submit" value="upload" />
        @ViewBag.Message

    </div>
}