StudManage1/Models/branch.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudManage1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branch()
        {
            this.stuDetails = new HashSet<stuDetail>();
        }
    
        public int bid { get; set; }
        public string b_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stuDetail> stuDetails { get; set; }
    }
}

StudManage1/Controllers/BranchController.cs
using StudManage1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebApplication1.Controllers
{
    [Authorize]
    public class BranchController : Controller
    {
        // GET: Branch
        public ActionResult Branches()
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            List<branch> lb = db.branches.ToList();

            return View(lb);
        }

        public ActionResult Students(int branchid, string searchString)
        {

            StudentManagement1Entities db = new StudentManagement1Entities();
            //List<stuDetail> lb = db.stuDetails.Where(s => s.cid == compid).ToList();
            var ModelList = new List<stuDetail>();

            using (var context = new StudentManagement1Entities())
            {
                var model = from s in context.stuDetails
                            select s;
                //Added this area to, Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.name.Contains(searchString)
                                           || s.gender.Contains(searchString));

                }
                model = model.OrderBy(s => s.name);
                ModelList = model.Where(s => s.branchId == branchid).ToList();


                return View(ModelList);

            }
        }
        [Authorize(Roles = "Admin,Teacher,PO")]
        public ActionResult Studentdeet(int sid)
        {
            StudentManagement1Entities db = new StudentManagement1Entities();
            eduDetail st = db.eduDetails.FirstOrDefault(s => s.id == sid);

            return View(st);
        }
    }
}

StudManage1/Controllers/HomePage2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudManage.Models
{
[Authorize]
    public class HomePage2Controller : Controller
    {
      
        // GET: HomePage2
        public ActionResult menu2()
        {
            return View();
        }
        public ActionResult regplace()
        {
            return View();
        }
        //Registrstion, branch, placement, result

    }
}

StudManage1/Views/Branch/Branches.cshtml
@model IEnumerable<StudManage1.Models.branch>
@using StudManage1.Models

@{ ViewBag.Title = "Branches"; }


<h2>BRANCHES</h2>

<style>
    div.w3-col {
        display: flex;
        padding: 25px;
        text-align: center;
        align-content: center
    }

    div.w3-container {
        background-color: white;
        /*border-radius: 20px;*/
    }

    img {
        width: 200px;
        height: 100px;
        align-content: center
    }

    a.option {
        border: 0px hidden gray;
        /*border-style: groove;*/
        margin: 10px;
        transition: transform .2s;
        color: blue;
        position: center;
        padding-bottom: 0px;
        align-content: center;
    }

    a:hover {
        transform: scale(1.3);
    }
</style>


<div class="w3-col l3 s6">
    <a class="option" href="~/Branch/Students?branchid=1">
        <div class="w3-container">
            <img src="https://careerswithstem.com.au/wp-content/uploads/2021/01/Should-I-study-computer-science.jpg">
            <p><b>Computer Science</b></p>
        </div>
    </a>
    <a class="option" href="~/Branch/Students?branchid=2">
        <div class="w3-container">
            <img src="https://images.shiksha.com/mediadata/images/articles/1565948235phpyxD4ZK.jpeg">
            <p><b>Information Science</b></p>
        </div>
    </a>
    <a class="option" href="~/Branch/Students?branchid=3">
        <div class="w3-container">
            <img src="https://chennai.vit.ac.in/wp-content/uploads/2021/09/What-is-Electronics-Engineering-Difference-Between-Electrical-and-Electronics-Engineering.jpg">
            <p><b>Electronics</b></p>
        </div>
    </a>
    <a class="option" href="~/Branch/Students?branchid=4">
        <div class="w3-container">
            <img src="https://www.avit.ac.in/img/mech1.jpg">
            <p><b>Mechanical</b></p>
        </div>
    </a>
    <a class="option" href="~/Branch/Students?branchid=5">
        <div class="w3-container">
            <img src="https://www.accurate.in/engg/img/page/civil-engineering-branch.jpg">
            <p><b>Civil</b></p>
        </div>
    </a>
</div>

@Html.ActionLink("BACK TO MENU", "menu2", "HomePage2")

StudManage1/Views/Branch/Studentdeet.cshtml
@model StudManage1.Models.eduDetail

@{
    ViewBag.Title = "Studentdeet";
}
<style>
    dl {
        margin-bottom: 50px;
    }

        dl dt {
            background: #5f9be3;
            color: #fff;
            float: left;
            font-weight: bold;
            margin-right: 10px;
            padding: 5px;
            width: 100px;
        }

        dl dd {
            margin: 2px 0;
            padding: 5px 0;
            
        }
    div.w3-row {
        display: flex;
    }

    div.w3-col {
        margin: 20px;
        
    }
    /*#left {
        float: left;
        width: 65%;
        overflow: hidden;
    }

    #right {
        overflow: hidden;
    }*/
</style>


<h2>Student Details</h2>
<hr />
<div class="w3-row">
    <div id="left" class="w3-col">


        <dl class="dl-horizontal">
            <dt>
                @*@Html.DisplayNameFor(model => model.stuDetail.rollNo)*@
                ROLL NUMBER:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.rollNo)
            </dd>

            <dt>
                @*@Html.DisplayNameFor(model => model.stuDetail.name)*@
                NAME:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.name)
            </dd>
            <dt>
                Date Of Birth:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.DOB)
            </dd>
            <dt>
                Age:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.age)
            </dd>

            <dt>
                Address:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.address)
            </dd>

            <dt>
                Phone Number
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.phoneNo)
            </dd>



            <dt>
                Gender:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.gender)
            </dd>

            <dt>
                City:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.city)
            </dd>
            <dt>
                Branch
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.branch.b_name)
            </dd>

            <dt>
                Placed In
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stuDetail.company.cname)
            </dd>


        </dl>
    </div>
    <div id="right" class="w3-col">
        <dl class="dl-horizontal">
            <dt>
                @*@Html.DisplayNameFor(model => model.ten_percent)*@
                Percentage achieved in 10th:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ten_percent)%
            </dd>

            <dt>
                Year of Passing 10th:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ten_yop)
            </dd>

            <dt>
                Attended 10th at Institution:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ten_inst)
            </dd>

            <dt>
                Percentage achieved in 12th:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.twel_percent)%
            </dd>

            <dt>
                Year of Passing 12th
            </dt>

            <dd>
                @Html.DisplayFor(model => model.twel_yop)
            </dd>

            <dt>
                Attended 10th at Institution:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.twel_inst)
            </dd>
            <dt>
                Current Semester:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.curr_sem)
            </dd>

            <dt>
                Present CGPA:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.curr_CGPA)
            </dd>


            

            @*<dt>
            GRADE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stuDetail.results)
        </dd>*@
        </dl>

    </div>
</div>
<a href="~/Branch/Branches">Go Back to list</a>

StudManage1/Views/Branch/Students.cshtml
@model IEnumerable<StudManage1.Models.stuDetail>
@using StudManage1.Models

@{
    ViewBag.Title = "stulist";
}

<h2>list</h2>
@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}


<ul>

    @foreach (stuDetail stuDetail in Model)

    {
    <li>

        @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("admin") || User.IsInRole("teacher")|| User.IsInRole("PO"))
                        {
                            @Html.ActionLink(stuDetail.name, "Studentdeet", "Branch", new { sid = stuDetail.sid }, null)
                        }
                        if (User.IsInRole("Student"))
                        { 
                            @stuDetail.name

                        }
                    }

    </li>
    }
</ul>


<p>
    @Html.ActionLink("Back to List", "Branches", "Branch")
</p>