StudManage1/Controllers/SignupController.cs
using CaptchaMvc.HtmlHelpers;
using StudManage1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StudManage.Controllers
{
    
    public class SignupController : Controller
    {
        // GET: Signup
        public ActionResult Index()
        {
            return View(new signup());
        }


        [HttpPost]
        public ActionResult Index(signup obj)
        {
           
                StudentManagement1Entities c = new StudentManagement1Entities();
                if (ModelState.IsValid)
                {
                    var isEmailAlreadyExists = c.signups.Any(x => x.username == obj.username);
                    if (isEmailAlreadyExists)
                    {


                        ModelState.AddModelError("Username", "User with this Name already exists");
                        return View(obj);
                    }
                    userrollmap var1 = new userrollmap();
                    var1.rid = 3;
                    var1.signupid = obj.signid;
                    c.signups.Add(obj);
                    c.userrollmaps.Add(var1);

                if (this.IsCaptchaValid("Captcha is not valid"))
                {
                    
                        c.SaveChanges();

                        return RedirectToAction("Login");
                    


                }
                else
                {
                    ViewBag.ErrMessage = "Error: captcha is not valid.";
                    return View(obj);
                }

                return RedirectToAction("Index");
                }
                return View(obj);
            
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(signup model)
        {
            using (StudentManagement1Entities context = new StudentManagement1Entities())
            {
                bool IsValidUser = context.signups.Any(user => user.username.ToLower() ==
                     model.username.ToLower() && user.pword == model.pword);
                if (IsValidUser)
                {
                    FormsAuthentication.SetAuthCookie(model.username, false);
                    return RedirectToAction("menu2", "HomePage2");
                }
                ModelState.AddModelError("", "invalid Username or Password");
                return View();
            }
        }
        public ActionResult forgot()
        {
            return View();
        }
        [HttpPost]
        public ActionResult forgot(signup r)
        {
            using (var abc = new StudentManagement1Entities())
            {
                bool IsValidUser = abc.signups.Any(x => x.username.ToLower() == r.username.ToLower());
                if (IsValidUser)
                {
                    var cols = abc.signups.Where(x => x.username.Equals(r.username));
                    foreach (signup c in cols)
                    {
                        c.pword = r.pword;
                        c.cpword = r.cpword;
                    }
                    abc.Configuration.ValidateOnSaveEnabled = false;
                    abc.SaveChanges();
                    return RedirectToAction("Login");
                }
                ModelState.AddModelError("", " Username does not exist!! ");
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        public ActionResult Login1(signup model)
        {
            using (StudentManagement1Entities context = new StudentManagement1Entities())
            {
                bool IsValidUser = context.signups.Any(user => user.username.ToLower() ==
                     model.username.ToLower() && user.pword == model.pword);
                if (IsValidUser)
                {
                    FormsAuthentication.SetAuthCookie(model.username, false);
                    return RedirectToAction("" +
                        "Index", "results");
                }
                ModelState.AddModelError("", "invalid Username or Password");
                return View();
            }
        }

    }
}

StudManage1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        img.logo{
            float:left;
            height:50px;
            width:200px;
            padding-right: 20px;
        }
        body {
            background-image: url(https://wallpaperaccess.com/full/1092570.jpg);
            /*background-image: url();*/
        }
        h1, h2, h3, h4, h5 {
            background-color: lightgray;
            font-family: Algerian;
            text-align:center;
        }
        p {
            background-color: lightgray;
            font-family:'Copperplate Gothic';
            
        }
        li{
            color:yellow;
        }
    </style>
</head>
<body>
    @*<div class="nav1">*@
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #DCDCDC; ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            <a href="~/HomePage1/Menu"><img class="logo" src="https://www.pngfind.com/pngs/m/613-6131136_2nd-convocation-ceremony-dit-university-dehradun-logo-hd.png" /></a>
            </div>
            <div class="navbar-collapse collapse" >
                <ul class="nav navbar-nav">
                    
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a style="color: black; font-family: Algerian; " href="~/HomePage2/menu2">HOME</a></li>
                        if (User.IsInRole("Student") || User.IsInRole("teacher"))
                        {
                            @*<li >@Html.ActionLink("Results Section", "Index", "results", new { style = "color:black;font-family:Algerian;" })</li>*@
                            <li><a style="color: black; font-family: Algerian; " href="~/results/Index">RESULT SECTION</a></li>
                        }
                        if (User.IsInRole("Student") || User.IsInRole("Admin"))
                        {
                            <li><a style="color: black; font-family: Algerian; " href="~/reg/Index">ADD STUDENT</a></li>

                            
                        }
                        @*<li >@Html.ActionLink("Student List", "Index", "stuDetails")</li>*@
                        <li><a style="color: black; font-family: Algerian; " href="~/stuDetails/Index">STUDENT LIST</a></li>
                        
                        <li><a style="color: black; font-family: Algerian; ">Hello - @User.Identity.Name</a></li>
                        @*<li>@Html.ActionLink("Logout", "Logout", "Signup", new { style = "color:black;font-family:Algerian;" })</li>*@
                        <li><a style="color: black; font-family: Algerian; " href="~/Signup/Logout">LOGOUT</a></li>

                    }
                    else
                    {
                        <li><a style="color: black; font-family: Algerian; " href="~/HomePage1/Menu">HOME</a></li>
                        @*<li>@Html.ActionLink("Login", "Login", "Signup", new { style = "color:black;font-family:Algerian;" })</li>*@
                        <li><a style="color: black; font-family: Algerian; " href="~/Signup/Login">LOGIN</a></li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Deepti Institute of Technology</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>